# Generated by Django 5.0.2 on 2025-09-30 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/perfil/usuario.png', upload_to='media/perfil')),
                ('balance', models.DecimalField(decimal_places=2, default=400000, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150)),
                ('stock_product', models.IntegerField(default=0)),
                ('price_product', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('img_product', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('valoration_product', models.IntegerField(default=0, null=True)),
                ('brand_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ecommerce.brand')),
                ('category_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2500)),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='Pucharse_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pucharse_order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_quantity', models.IntegerField(default=1)),
                ('detail_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detail_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detail_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app_ecommerce.pucharse_order')),
                ('detail_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='valoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
