# Generated by Django 5.0.2 on 2025-09-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pucharse_order',
            table='app_ecommerce_pucharse_order',
        ),
    ]
