# Generated by Django 5.0.2 on 2025-10-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0002_alter_pucharse_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='perfil/usuario.png', upload_to='perfil/'),
        ),
    ]
