# Generated by Django 5.0.2 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0003_alter_perfil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
