# Generated by Django 5.0.2 on 2025-10-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0004_alter_perfil_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pucharse_order',
            name='n_invoice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
