# Generated by Django 5.0.2 on 2025-10-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0005_pucharse_order_n_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pucharse_order',
            name='n_invoice',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
