# Generated by Django 5.0.2 on 2025-10-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0006_alter_pucharse_order_n_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pucharse_order',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
