# Generated by Django 5.0.2 on 2025-10-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0007_pucharse_order_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pucharse_order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
