# Generated by Django 5.0.2 on 2025-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0008_pucharse_order_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=300000, max_digits=12),
        ),
    ]
