# Generated by Django 5.2.7 on 2025-10-31 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0009_alter_perfil_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoration',
            unique_together={('user', 'product')},
        ),
    ]
