# Generated by Django 5.2.7 on 2025-11-08 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0010_alter_valoration_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='valoration',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_valoration'),
        ),
    ]
