# Generated by Django 5.2.7 on 2025-11-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0011_alter_valoration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name_brand',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
