# Generated by Django 5.2.7 on 2025-11-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0012_alter_brand_name_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
