# Generated by Django 5.2.8 on 2025-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0014_alter_comments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name_product',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
