# Generated by Django 5.2.8 on 2025-12-01 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0015_alter_products_name_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='valoration',
            name='unique_user_product_valoration',
        ),
        migrations.AddConstraint(
            model_name='valoration',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_valoration_constraint'),
        ),
    ]
