# Generated by Django 5.2.8 on 2025-12-01 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0016_remove_valoration_unique_user_product_valoration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='valoration',
            name='unique_valoration_constraint',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_valoration_constraint', violation_error_message='No puedes valorar un mismo producto 2 veces'),
        ),
    ]
