# Generated by Django 5.2.8 on 2026-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0018_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pucharse_order',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=10, null=True),
        ),
    ]
